export const GET_ALL_DOODLES_REQUEST = 'GET_ALL_DOODLES_REQUEST';
export const GET_ALL_DOODLES_SUCCESS = 'GET_ALL_DOODLES_SUCCESS';
export const GET_ALL_DOODLES_ERROR = 'GET_ALL_DOODLES_ERROR';

export const ADD_DOODLE_SEARCH_CRITERIA = 'ADD_DOODLE_SEARCH_CRITERIA';

export const SOLD_BOOLEAN_SEARCH_CRITERIA = 'SOLD_BOOLEAN_SEARCH_CRITERIA';

export const DATE_BOOLEAN_SEARCH_CRITERIA = 'DATE_BOOLEAN_SEARCH_CRITERIA';

export const ADD_HOME_PAGE_SEARCH_TERM = 'ADD_HOME_PAGE_SEARCH_TERM';
